kind: pipeline
name: default

steps:
- name: build
  image: node:latest
  commands:
  - npm ci
  - bash ./drone/gh-pages.sh
  environment:
    DECRYPT_KEY:
      from_secret: GH_PAGES_KEY
    COMMIT_AUTHOR_EMAIL: "sh@signalwerk.ch"
    DEPLOY_DIR: "build"
    SOURCE_BRANCH: "master"
    TARGET_BRANCH: "gh-pages"
  when:
    branch:
    - master
